(define-module (xyz jackfaller discord)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages cups)
  #:use-module (gnu packages fontutils)
  #:use-module (gnu packages freedesktop)
  #:use-module (gnu packages gcc)
  #:use-module (gnu packages gl)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages kerberos)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages node)
  #:use-module (gnu packages nss)
  #:use-module (gnu packages pulseaudio)
  #:use-module (gnu packages video)
  #:use-module (gnu packages wget)
  #:use-module (gnu packages xdisorg)
  #:use-module (gnu packages xml)
  #:use-module (gnu packages xorg)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module ((guix licenses) :prefix license:)
  #:use-module (guix packages)
  #:use-module (guix utils)
  #:use-module (ice-9 match)
  #:use-module (nonguix build-system chromium-binary)
  #:use-module ((nonguix licenses) :prefix license:))

;; Generated by `update-discord-info.sh`.
;; begin generated content
(define discord-version "1.0.151")
(define discord-hash "18hg5p9rq2p1g6fpm05bl9izr2kz3wccf381nk28qywc3cb9f2i4")
(define discord-uri "https://stable.dl2.discordapp.net/distro/app/stable/linux/x64/1.0.151/full.distro")
(define stub-uri "https://cdn.discordapp.com/apps/linux/1.0.151/discord-1.0.151.tar.gz")
(define stub-hash "114zyj4l37bh1gyy6kkfgffbxjpfc4cyf5ky0vlq5v9qbnp3yy4x")
(define module-uris '("https://stable.dl2.discordapp.net/distro/app/stable/linux/x64/1.0.151/discord_desktop_core/1/full.distro" "https://stable.dl2.discordapp.net/distro/app/stable/linux/x64/1.0.151/discord_erlpack/1/full.distro" "https://stable.dl2.discordapp.net/distro/app/stable/linux/x64/1.0.151/discord_spellcheck/1/full.distro" "https://stable.dl2.discordapp.net/distro/app/stable/linux/x64/1.0.151/discord_utils/1/full.distro" "https://stable.dl2.discordapp.net/distro/app/stable/linux/x64/1.0.151/discord_voice/1/full.distro"))
(define module-hashes '("0lad10cpmh3c4qqa889m2d6dldf30s5xb9mbqgs1d8cqhv9px2vs" "1qkza6255v8dkirz5h5zagplrywrbaxjz9ydbh01lnb48vhqg37k" "02f6hznq2srxvvjs3dgp1jkrnr4xh6dy8dx2ga1l3pabxb31ndw5" "1bbm6ypnn9286wiv8dijjs0fmvdqw120fz0x31qcn4cxcjn9ykc9" "16npgxi7hrb4icxzvhhjgxaj3krhs7gv1p9fgbjbgk6ngninp4bs"))
(define module-names '("discord_desktop_core" "discord_erlpack" "discord_spellcheck" "discord_utils" "discord_voice"))
;; end generated content

(define discord-stub
  (origin (method url-fetch) (uri stub-uri) (sha256 (base32 stub-hash))))

;; This is a dummy package which fetches the modules Discord needs.
;; Each module has a source which is a Brotli compressed tar file.
;; Decompress each of those files, then recompress them as zip files which is
;; what the client expects.
(define discord-modules
  (package
    (name "discord-modules")
    (version discord-version)
    (source
     (file-union
      "modules"
      (map (lambda (name uri hash)
             (list
              (string-append name ".br")
              (origin (method url-fetch) (uri uri) (sha256 (base32 hash)))))
           module-names module-uris module-hashes)))
    (build-system (@ (guix build-system copy) copy-build-system))
    (arguments
     (list
      #:install-plan
      #~(map (lambda (name)
               (let ((f (string-append name ".zip"))) (list f f)))
             '#$module-names)
      #:phases
      (with-imported-modules '((guix build utils))
        #~(modify-phases %standard-phases
            (add-after 'unpack 'brotli-repack-to-zip
              (lambda* (#:key #:allow-other-keys)
                (use-modules (guix build utils))
                (for-each
                 (lambda (name)
                   (invoke
                    "sh" "-c"
                    (string-append
                     "brotli --decompress --stdout " name ".br"
                     " | tar x"
                     "; cd files"
                     "; 7z a ../" name ".zip *"
                     "; cd .."
                     "; rm -rf files")))
                 '#$module-names)))))))
    (native-inputs (list brotli tar 7zip))
    (synopsis "Discord modules")
    (description "Discord modules")
    (license (license:nonfree "https://discord.com/terms"))
    (home-page "https://discordapp.com")))

(define-public discord
  (package
   (name "discord")
   (version discord-version)
   (source
    (origin
      (method url-fetch)
      (uri discord-uri)
      (sha256
       (base32 discord-hash))))
   ;; Use this build system to set XDG_DATA_DIRS and other variables.
   (build-system chromium-binary-build-system)
   (arguments
    (list
     #:patchelf-plan
     #~`(("Discord") ("chrome_crashpad_handler") ("chrome-sandbox"))
     #:install-plan
     #~`(("." "opt/discord")
         (#$discord-modules "opt/discord/resources/bootstrap")
         ("discord.desktop" "/share/applications/")
         ("discord.sh" "bin/discord")
         ("discord.png" "share/icons/hicolor/256x256/apps/")
         ("discord.png" "share/pixmaps/"))
     #:phases
     (with-imported-modules '((guix build utils))
       #~(modify-phases %standard-phases
           (add-after 'unpack 'brotli-unpack
             (lambda* (#:key #:allow-other-keys)
               (use-modules (guix build utils))
               (invoke "sh" "-c" "brotli --decompress --stdout full.distro | tar x; mv files/* .")))
           (add-after 'binary-unpack 'setup-cwd
             (lambda* (#:key outputs #:allow-other-keys)
               (use-modules (guix build utils))
               (define output (assoc-ref outputs "out"))
               ;; Patch the desktop file from the stub installer.
               (define temp (mkdtemp "extract-result.XXXXXX"))
               (invoke "tar" "xzf" #$discord-stub "-C" temp "Discord/discord.desktop")
               (invoke "mv" (string-append temp "/Discord/discord.desktop") ".")
               (delete-file-recursively temp)
               (substitute* "discord.desktop"
                 (("Exec=.*$")
                  (string-append "Exec=" output "/bin/discord\n"))
                 (("Path=.*$")
                  (string-append "Path=" output "/opt/discord\n")))
               (with-output-to-file "discord.sh"
                 (lambda _
                   (define (line . args)
                     (display (apply string-append args)) (newline))
                   (line "#!/bin/sh")
                   (line "cd " output "/opt/discord")
                   (line "./Discord"
                         ;; Always use Ozone on Wayland, not sure if this is a good idea.
                         " ${WAYLAND_DISPLAY:+--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer}"
                         " \"$@\"")))
               (for-each
                (lambda (f) (chmod f #o755))
                '("Discord" "chrome_crashpad_handler" "chrome-sandbox"
                  "discord.sh"))))))))
   (native-inputs (list brotli tar))
   (inputs (list ffmpeg
                 gdk-pixbuf
                 libappindicator
                 libdbusmenu
                 libglvnd
                 libxscrnsaver
                 util-linux
                 wayland
                 ;; Not sure if all of these are needed.
                 gzip
                 libsm
                 node
                 pipewire
                 pulseaudio
                 unzip
                 wget
                 xdg-utils))
   (synopsis "Discord chat client")
   (description "All-in-one cross-platform voice and text chat for gamers.")
   (license (license:nonfree "https://discord.com/terms"))
   (home-page "https://discordapp.com")))
discord
